# Generated by Django 3.0.5 on 2020-06-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('super_powers', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='weapon',
            name='power',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemies',
            field=models.ManyToManyField(to='main_app.Enemy'),
        ),
    ]
